// src/components/common/countries.js
// Liste complète des pays (nom FR, code ISO2, indicatif téléphonique, nationalité FR).
// Partagée par PhoneInput (indicatif) et CountrySelect (nationalité).
// Triée alphabétiquement par nom français.

export const COUNTRIES = [
  { code: "af", name: "Afghanistan", dial: "+93", nat: "Afghane" },
  { code: "za", name: "Afrique du Sud", dial: "+27", nat: "Sud-Africaine" },
  { code: "al", name: "Albanie", dial: "+355", nat: "Albanaise" },
  { code: "dz", name: "Algérie", dial: "+213", nat: "Algérienne" },
  { code: "de", name: "Allemagne", dial: "+49", nat: "Allemande" },
  { code: "ad", name: "Andorre", dial: "+376", nat: "Andorrane" },
  { code: "ao", name: "Angola", dial: "+244", nat: "Angolaise" },
  { code: "ag", name: "Antigua-et-Barbuda", dial: "+1268", nat: "Antiguaise" },
  { code: "sa", name: "Arabie saoudite", dial: "+966", nat: "Saoudienne" },
  { code: "ar", name: "Argentine", dial: "+54", nat: "Argentine" },
  { code: "am", name: "Arménie", dial: "+374", nat: "Arménienne" },
  { code: "au", name: "Australie", dial: "+61", nat: "Australienne" },
  { code: "at", name: "Autriche", dial: "+43", nat: "Autrichienne" },
  { code: "az", name: "Azerbaïdjan", dial: "+994", nat: "Azerbaïdjanaise" },
  { code: "bs", name: "Bahamas", dial: "+1242", nat: "Bahaméenne" },
  { code: "bh", name: "Bahreïn", dial: "+973", nat: "Bahreïnienne" },
  { code: "bd", name: "Bangladesh", dial: "+880", nat: "Bangladaise" },
  { code: "bb", name: "Barbade", dial: "+1246", nat: "Barbadienne" },
  { code: "be", name: "Belgique", dial: "+32", nat: "Belge" },
  { code: "bz", name: "Belize", dial: "+501", nat: "Bélizienne" },
  { code: "bj", name: "Bénin", dial: "+229", nat: "Béninoise" },
  { code: "bt", name: "Bhoutan", dial: "+975", nat: "Bhoutanaise" },
  { code: "by", name: "Biélorussie", dial: "+375", nat: "Biélorusse" },
  { code: "mm", name: "Birmanie (Myanmar)", dial: "+95", nat: "Birmane" },
  { code: "bo", name: "Bolivie", dial: "+591", nat: "Bolivienne" },
  { code: "ba", name: "Bosnie-Herzégovine", dial: "+387", nat: "Bosnienne" },
  { code: "bw", name: "Botswana", dial: "+267", nat: "Botswanaise" },
  { code: "br", name: "Brésil", dial: "+55", nat: "Brésilienne" },
  { code: "bn", name: "Brunei", dial: "+673", nat: "Brunéienne" },
  { code: "bg", name: "Bulgarie", dial: "+359", nat: "Bulgare" },
  { code: "bf", name: "Burkina Faso", dial: "+226", nat: "Burkinabè" },
  { code: "bi", name: "Burundi", dial: "+257", nat: "Burundaise" },
  { code: "kh", name: "Cambodge", dial: "+855", nat: "Cambodgienne" },
  { code: "cm", name: "Cameroun", dial: "+237", nat: "Camerounaise" },
  { code: "ca", name: "Canada", dial: "+1", nat: "Canadienne" },
  { code: "cv", name: "Cap-Vert", dial: "+238", nat: "Cap-Verdienne" },
  { code: "cf", name: "Centrafrique", dial: "+236", nat: "Centrafricaine" },
  { code: "cl", name: "Chili", dial: "+56", nat: "Chilienne" },
  { code: "cn", name: "Chine", dial: "+86", nat: "Chinoise" },
  { code: "cy", name: "Chypre", dial: "+357", nat: "Chypriote" },
  { code: "co", name: "Colombie", dial: "+57", nat: "Colombienne" },
  { code: "km", name: "Comores", dial: "+269", nat: "Comorienne" },
  { code: "cg", name: "Congo-Brazzaville", dial: "+242", nat: "Congolaise (Brazza)" },
  { code: "kp", name: "Corée du Nord", dial: "+850", nat: "Nord-Coréenne" },
  { code: "kr", name: "Corée du Sud", dial: "+82", nat: "Sud-Coréenne" },
  { code: "cr", name: "Costa Rica", dial: "+506", nat: "Costaricaine" },
  { code: "ci", name: "Côte d'Ivoire", dial: "+225", nat: "Ivoirienne" },
  { code: "hr", name: "Croatie", dial: "+385", nat: "Croate" },
  { code: "cu", name: "Cuba", dial: "+53", nat: "Cubaine" },
  { code: "dk", name: "Danemark", dial: "+45", nat: "Danoise" },
  { code: "dj", name: "Djibouti", dial: "+253", nat: "Djiboutienne" },
  { code: "dm", name: "Dominique", dial: "+1767", nat: "Dominiquaise" },
  { code: "eg", name: "Égypte", dial: "+20", nat: "Égyptienne" },
  { code: "ae", name: "Émirats arabes unis", dial: "+971", nat: "Émirienne" },
  { code: "ec", name: "Équateur", dial: "+593", nat: "Équatorienne" },
  { code: "er", name: "Érythrée", dial: "+291", nat: "Érythréenne" },
  { code: "es", name: "Espagne", dial: "+34", nat: "Espagnole" },
  { code: "ee", name: "Estonie", dial: "+372", nat: "Estonienne" },
  { code: "sz", name: "Eswatini", dial: "+268", nat: "Swazie" },
  { code: "us", name: "États-Unis", dial: "+1", nat: "Américaine" },
  { code: "et", name: "Éthiopie", dial: "+251", nat: "Éthiopienne" },
  { code: "fj", name: "Fidji", dial: "+679", nat: "Fidjienne" },
  { code: "fi", name: "Finlande", dial: "+358", nat: "Finlandaise" },
  { code: "fr", name: "France", dial: "+33", nat: "Française" },
  { code: "ga", name: "Gabon", dial: "+241", nat: "Gabonaise" },
  { code: "gm", name: "Gambie", dial: "+220", nat: "Gambienne" },
  { code: "ge", name: "Géorgie", dial: "+995", nat: "Géorgienne" },
  { code: "gh", name: "Ghana", dial: "+233", nat: "Ghanéenne" },
  { code: "gr", name: "Grèce", dial: "+30", nat: "Grecque" },
  { code: "gd", name: "Grenade", dial: "+1473", nat: "Grenadienne" },
  { code: "gt", name: "Guatemala", dial: "+502", nat: "Guatémaltèque" },
  { code: "gn", name: "Guinée", dial: "+224", nat: "Guinéenne" },
  { code: "gq", name: "Guinée équatoriale", dial: "+240", nat: "Équato-guinéenne" },
  { code: "gw", name: "Guinée-Bissau", dial: "+245", nat: "Bissau-Guinéenne" },
  { code: "gy", name: "Guyana", dial: "+592", nat: "Guyanienne" },
  { code: "ht", name: "Haïti", dial: "+509", nat: "Haïtienne" },
  { code: "hn", name: "Honduras", dial: "+504", nat: "Hondurienne" },
  { code: "hu", name: "Hongrie", dial: "+36", nat: "Hongroise" },
  { code: "mh", name: "Îles Marshall", dial: "+692", nat: "Marshallaise" },
  { code: "sb", name: "Îles Salomon", dial: "+677", nat: "Salomonaise" },
  { code: "in", name: "Inde", dial: "+91", nat: "Indienne" },
  { code: "id", name: "Indonésie", dial: "+62", nat: "Indonésienne" },
  { code: "iq", name: "Irak", dial: "+964", nat: "Irakienne" },
  { code: "ir", name: "Iran", dial: "+98", nat: "Iranienne" },
  { code: "ie", name: "Irlande", dial: "+353", nat: "Irlandaise" },
  { code: "is", name: "Islande", dial: "+354", nat: "Islandaise" },
  { code: "il", name: "Israël", dial: "+972", nat: "Israélienne" },
  { code: "it", name: "Italie", dial: "+39", nat: "Italienne" },
  { code: "jm", name: "Jamaïque", dial: "+1876", nat: "Jamaïcaine" },
  { code: "jp", name: "Japon", dial: "+81", nat: "Japonaise" },
  { code: "jo", name: "Jordanie", dial: "+962", nat: "Jordanienne" },
  { code: "kz", name: "Kazakhstan", dial: "+7", nat: "Kazakhe" },
  { code: "ke", name: "Kenya", dial: "+254", nat: "Kényane" },
  { code: "kg", name: "Kirghizistan", dial: "+996", nat: "Kirghize" },
  { code: "ki", name: "Kiribati", dial: "+686", nat: "Kiribatienne" },
  { code: "xk", name: "Kosovo", dial: "+383", nat: "Kosovare" },
  { code: "kw", name: "Koweït", dial: "+965", nat: "Koweïtienne" },
  { code: "la", name: "Laos", dial: "+856", nat: "Laotienne" },
  { code: "ls", name: "Lesotho", dial: "+266", nat: "Lesothane" },
  { code: "lv", name: "Lettonie", dial: "+371", nat: "Lettone" },
  { code: "lb", name: "Liban", dial: "+961", nat: "Libanaise" },
  { code: "lr", name: "Liberia", dial: "+231", nat: "Libérienne" },
  { code: "ly", name: "Libye", dial: "+218", nat: "Libyenne" },
  { code: "li", name: "Liechtenstein", dial: "+423", nat: "Liechtensteinoise" },
  { code: "lt", name: "Lituanie", dial: "+370", nat: "Lituanienne" },
  { code: "lu", name: "Luxembourg", dial: "+352", nat: "Luxembourgeoise" },
  { code: "mk", name: "Macédoine du Nord", dial: "+389", nat: "Macédonienne" },
  { code: "mg", name: "Madagascar", dial: "+261", nat: "Malgache" },
  { code: "my", name: "Malaisie", dial: "+60", nat: "Malaisienne" },
  { code: "mw", name: "Malawi", dial: "+265", nat: "Malawienne" },
  { code: "mv", name: "Maldives", dial: "+960", nat: "Maldivienne" },
  { code: "ml", name: "Mali", dial: "+223", nat: "Malienne" },
  { code: "mt", name: "Malte", dial: "+356", nat: "Maltaise" },
  { code: "ma", name: "Maroc", dial: "+212", nat: "Marocaine" },
  { code: "mu", name: "Maurice", dial: "+230", nat: "Mauricienne" },
  { code: "mr", name: "Mauritanie", dial: "+222", nat: "Mauritanienne" },
  { code: "mx", name: "Mexique", dial: "+52", nat: "Mexicaine" },
  { code: "fm", name: "Micronésie", dial: "+691", nat: "Micronésienne" },
  { code: "md", name: "Moldavie", dial: "+373", nat: "Moldave" },
  { code: "mc", name: "Monaco", dial: "+377", nat: "Monégasque" },
  { code: "mn", name: "Mongolie", dial: "+976", nat: "Mongole" },
  { code: "me", name: "Monténégro", dial: "+382", nat: "Monténégrine" },
  { code: "mz", name: "Mozambique", dial: "+258", nat: "Mozambicaine" },
  { code: "na", name: "Namibie", dial: "+264", nat: "Namibienne" },
  { code: "nr", name: "Nauru", dial: "+674", nat: "Nauruane" },
  { code: "np", name: "Népal", dial: "+977", nat: "Népalaise" },
  { code: "ni", name: "Nicaragua", dial: "+505", nat: "Nicaraguayenne" },
  { code: "ne", name: "Niger", dial: "+227", nat: "Nigérienne" },
  { code: "ng", name: "Nigéria", dial: "+234", nat: "Nigériane" },
  { code: "no", name: "Norvège", dial: "+47", nat: "Norvégienne" },
  { code: "nz", name: "Nouvelle-Zélande", dial: "+64", nat: "Néo-Zélandaise" },
  { code: "om", name: "Oman", dial: "+968", nat: "Omanaise" },
  { code: "ug", name: "Ouganda", dial: "+256", nat: "Ougandaise" },
  { code: "uz", name: "Ouzbékistan", dial: "+998", nat: "Ouzbèke" },
  { code: "pk", name: "Pakistan", dial: "+92", nat: "Pakistanaise" },
  { code: "pw", name: "Palaos", dial: "+680", nat: "Palaoise" },
  { code: "ps", name: "Palestine", dial: "+970", nat: "Palestinienne" },
  { code: "pa", name: "Panama", dial: "+507", nat: "Panaméenne" },
  { code: "pg", name: "Papouasie-Nouvelle-Guinée", dial: "+675", nat: "Papouane" },
  { code: "py", name: "Paraguay", dial: "+595", nat: "Paraguayenne" },
  { code: "nl", name: "Pays-Bas", dial: "+31", nat: "Néerlandaise" },
  { code: "pe", name: "Pérou", dial: "+51", nat: "Péruvienne" },
  { code: "ph", name: "Philippines", dial: "+63", nat: "Philippine" },
  { code: "pl", name: "Pologne", dial: "+48", nat: "Polonaise" },
  { code: "pt", name: "Portugal", dial: "+351", nat: "Portugaise" },
  { code: "qa", name: "Qatar", dial: "+974", nat: "Qatarienne" },
  { code: "cd", name: "RD Congo", dial: "+243", nat: "Congolaise" },
  { code: "do", name: "République dominicaine", dial: "+1809", nat: "Dominicaine" },
  { code: "cz", name: "République tchèque", dial: "+420", nat: "Tchèque" },
  { code: "ro", name: "Roumanie", dial: "+40", nat: "Roumaine" },
  { code: "gb", name: "Royaume-Uni", dial: "+44", nat: "Britannique" },
  { code: "ru", name: "Russie", dial: "+7", nat: "Russe" },
  { code: "rw", name: "Rwanda", dial: "+250", nat: "Rwandaise" },
  { code: "kn", name: "Saint-Kitts-et-Nevis", dial: "+1869", nat: "Kittitienne" },
  { code: "sm", name: "Saint-Marin", dial: "+378", nat: "Saint-Marinaise" },
  { code: "vc", name: "Saint-Vincent-et-les-Grenadines", dial: "+1784", nat: "Vincentaise" },
  { code: "lc", name: "Sainte-Lucie", dial: "+1758", nat: "Saint-Lucienne" },
  { code: "sv", name: "Salvador", dial: "+503", nat: "Salvadorienne" },
  { code: "ws", name: "Samoa", dial: "+685", nat: "Samoane" },
  { code: "st", name: "Sao Tomé-et-Principe", dial: "+239", nat: "Santoméenne" },
  { code: "sn", name: "Sénégal", dial: "+221", nat: "Sénégalaise" },
  { code: "rs", name: "Serbie", dial: "+381", nat: "Serbe" },
  { code: "sc", name: "Seychelles", dial: "+248", nat: "Seychelloise" },
  { code: "sl", name: "Sierra Leone", dial: "+232", nat: "Sierra-Léonaise" },
  { code: "sg", name: "Singapour", dial: "+65", nat: "Singapourienne" },
  { code: "sk", name: "Slovaquie", dial: "+421", nat: "Slovaque" },
  { code: "si", name: "Slovénie", dial: "+386", nat: "Slovène" },
  { code: "so", name: "Somalie", dial: "+252", nat: "Somalienne" },
  { code: "sd", name: "Soudan", dial: "+249", nat: "Soudanaise" },
  { code: "ss", name: "Soudan du Sud", dial: "+211", nat: "Sud-Soudanaise" },
  { code: "lk", name: "Sri Lanka", dial: "+94", nat: "Sri-Lankaise" },
  { code: "se", name: "Suède", dial: "+46", nat: "Suédoise" },
  { code: "ch", name: "Suisse", dial: "+41", nat: "Suisse" },
  { code: "sr", name: "Suriname", dial: "+597", nat: "Surinamaise" },
  { code: "sy", name: "Syrie", dial: "+963", nat: "Syrienne" },
  { code: "tj", name: "Tadjikistan", dial: "+992", nat: "Tadjike" },
  { code: "tz", name: "Tanzanie", dial: "+255", nat: "Tanzanienne" },
  { code: "td", name: "Tchad", dial: "+235", nat: "Tchadienne" },
  { code: "th", name: "Thaïlande", dial: "+66", nat: "Thaïlandaise" },
  { code: "tl", name: "Timor oriental", dial: "+670", nat: "Est-Timoraise" },
  { code: "tg", name: "Togo", dial: "+228", nat: "Togolaise" },
  { code: "to", name: "Tonga", dial: "+676", nat: "Tongienne" },
  { code: "tt", name: "Trinité-et-Tobago", dial: "+1868", nat: "Trinidadienne" },
  { code: "tn", name: "Tunisie", dial: "+216", nat: "Tunisienne" },
  { code: "tm", name: "Turkménistan", dial: "+993", nat: "Turkmène" },
  { code: "tr", name: "Turquie", dial: "+90", nat: "Turque" },
  { code: "tv", name: "Tuvalu", dial: "+688", nat: "Tuvaluane" },
  { code: "ua", name: "Ukraine", dial: "+380", nat: "Ukrainienne" },
  { code: "uy", name: "Uruguay", dial: "+598", nat: "Uruguayenne" },
  { code: "vu", name: "Vanuatu", dial: "+678", nat: "Vanuataise" },
  { code: "va", name: "Vatican", dial: "+379", nat: "Vaticane" },
  { code: "ve", name: "Venezuela", dial: "+58", nat: "Vénézuélienne" },
  { code: "vn", name: "Vietnam", dial: "+84", nat: "Vietnamienne" },
  { code: "ye", name: "Yémen", dial: "+967", nat: "Yéménite" },
  { code: "zm", name: "Zambie", dial: "+260", nat: "Zambienne" },
  { code: "zw", name: "Zimbabwe", dial: "+263", nat: "Zimbabwéenne" },
];

export const DEFAULT_COUNTRY =
  COUNTRIES.find((c) => c.code === "cd") ?? COUNTRIES[0];
